import { Link, useForm } from '@inertiajs/react';
import { Banknote, Clock3, Fingerprint, ShieldCheck } from 'lucide-react';
import type { FormEvent } from 'react';
import PageFrame from '../../components/PageFrame';
import PageHeader from '../../components/PageHeader';
import AppLayout from '../../layouts/AppLayout';

type LeaveType = { id: number; code: string; name: string; tracks_balance: boolean; balance?: string | null; entitlement_label?: string | null };
type LeaveRequest = { id: number; start_date: string; end_date: string; units: string; status: string; leave_type: LeaveType };
type Attendance = { id: number; occurred_at: string; event_type: string; source: string };
type Integration = { source: string; status: string; lastEvent?: string | null; events: number; employeesRepresented: number };

const fieldClass = 'w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-[12px] text-slate-900 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-700/20 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-100 sm:px-4 sm:py-3 sm:text-sm';

export default function Dashboard({ employee, department, leaveTypes, requests, attendance, canAdmin, attendanceIntegration }: any) {
    const integration = attendanceIntegration as Integration;
    const form = useForm({ leave_type_id: leaveTypes[0]?.id ?? '', start_date: '', end_date: '', units: 1, reason: '' });
    const submit = (e: FormEvent) => { e.preventDefault(); form.post('/hris/leave-requests', { preserveScroll: true, onSuccess: () => form.reset('start_date', 'end_date', 'reason') }); };
    const actions = <div className="flex flex-wrap gap-2"><Link href="/hris/dtr" className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-blue-200 bg-white px-3 text-[11px] font-semibold text-blue-800 focus:outline-none focus:ring-2 focus:ring-blue-700/30 dark:border-blue-900 dark:bg-[#142236] dark:text-blue-300 sm:px-4 sm:text-sm"><Clock3 size={15} /> DTR</Link><Link href="/hris/payroll" className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-blue-200 bg-white px-3 text-[11px] font-semibold text-blue-800 focus:outline-none focus:ring-2 focus:ring-blue-700/30 dark:border-blue-900 dark:bg-[#142236] dark:text-blue-300 sm:px-4 sm:text-sm"><Banknote size={15} /> Payroll</Link>{canAdmin && <Link href="/hris/admin" className="inline-flex min-h-10 items-center rounded-xl bg-[#0b2852] px-3 text-[11px] font-semibold text-white focus:outline-none focus:ring-2 focus:ring-blue-700/30 sm:px-4 sm:text-sm">HR Administration</Link>}</div>;

    return <AppLayout title="HRIS"><PageFrame>
        <PageHeader eyebrow="Employee services" title="My HR Record" description={`${employee.employee_number} · ${employee.position_title} · ${department.name}. Review leave, attendance evidence, DTR, and payroll information available to your current role.`} icon={Fingerprint} aside={actions} />

        <section className="grid grid-cols-2 gap-2.5 sm:grid-cols-3 sm:gap-4 lg:grid-cols-5" aria-label="Leave balances">
            {leaveTypes.map((type: LeaveType) => <div key={type.id} className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-700 dark:bg-[#142236] sm:rounded-2xl sm:p-5"><div className="text-[9px] font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400 sm:text-xs">{type.code}</div><div className="mt-1 text-[11px] font-semibold text-slate-900 dark:text-slate-100 sm:mt-2 sm:text-sm">{type.name}</div><div className="mt-2 text-lg font-bold text-blue-900 dark:text-blue-300 sm:mt-4 sm:text-2xl">{type.tracks_balance ? `${Number(type.balance || 0).toFixed(3)}` : (type.entitlement_label || 'Policy-based')}</div><div className="mt-0.5 text-[9px] text-slate-400 dark:text-slate-500 sm:mt-1 sm:text-xs">{type.tracks_balance ? 'available credits' : 'entitlement'}</div></div>)}
        </section>

        <section className="grid gap-4 xl:grid-cols-[1fr_.9fr]">
            <form onSubmit={submit} aria-label="Leave request" className="space-y-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-[#142236] sm:space-y-5 sm:rounded-3xl sm:p-6"><div><h2 className="text-sm font-bold text-slate-950 dark:text-slate-100 sm:text-base">Apply for leave</h2><p className="mt-1 text-[10px] text-slate-500 dark:text-slate-400 sm:text-sm">Requested units remain subject to HR verification and approval.</p></div><label className="block"><span className="mb-1.5 block text-[11px] font-semibold text-slate-700 dark:text-slate-300 sm:text-sm">Leave type</span><select value={form.data.leave_type_id} onChange={(e) => form.setData('leave_type_id', Number(e.target.value))} className={fieldClass}>{leaveTypes.map((type: LeaveType) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1.5 block text-[11px] font-semibold text-slate-700 dark:text-slate-300 sm:text-sm">From</span><input type="date" value={form.data.start_date} onChange={(e) => form.setData('start_date', e.target.value)} className={fieldClass} /></label><label><span className="mb-1.5 block text-[11px] font-semibold text-slate-700 dark:text-slate-300 sm:text-sm">To</span><input type="date" value={form.data.end_date} onChange={(e) => form.setData('end_date', e.target.value)} className={fieldClass} /></label></div><label className="block"><span className="mb-1.5 block text-[11px] font-semibold text-slate-700 dark:text-slate-300 sm:text-sm">Leave units</span><input type="number" step="0.5" min="0.5" value={form.data.units} onChange={(e) => form.setData('units', Number(e.target.value))} className={fieldClass} /></label><label className="block"><span className="mb-1.5 block text-[11px] font-semibold text-slate-700 dark:text-slate-300 sm:text-sm">Reason</span><textarea rows={3} value={form.data.reason} onChange={(e) => form.setData('reason', e.target.value)} className={fieldClass} /></label><button disabled={form.processing} className="rounded-xl bg-[#0b2852] px-4 py-2.5 text-[11px] font-semibold text-white focus:outline-none focus:ring-2 focus:ring-blue-700/30 disabled:opacity-60 sm:px-5 sm:py-3 sm:text-sm">Submit leave request</button></form>

            <div className="space-y-4 sm:space-y-6">
                <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-[#142236] sm:rounded-3xl sm:p-6" aria-labelledby="recent-leave-title"><h2 id="recent-leave-title" className="text-sm font-bold text-slate-950 dark:text-slate-100 sm:text-base">Recent leave requests</h2><div className="mt-3 divide-y divide-slate-100 dark:divide-slate-700 sm:mt-4">{requests.map((r: LeaveRequest) => <div key={r.id} className="py-2.5 sm:py-3"><div className="flex justify-between gap-3"><div><div className="text-[11px] font-semibold text-slate-900 dark:text-slate-100 sm:text-sm">{r.leave_type.name}</div><div className="mt-1 text-[9px] text-slate-500 dark:text-slate-400 sm:text-xs">{new Date(r.start_date).toLocaleDateString()} – {new Date(r.end_date).toLocaleDateString()} · {Number(r.units).toFixed(1)} units</div></div><span className="h-fit rounded-full bg-slate-100 px-2 py-1 text-[8px] font-bold uppercase text-slate-700 dark:bg-slate-800 dark:text-slate-300 sm:px-2.5 sm:text-[10px]">{r.status}</span></div></div>)}{requests.length === 0 && <div className="py-4 text-[11px] text-slate-500 dark:text-slate-400 sm:py-5 sm:text-sm">No leave requests yet.</div>}</div></section>

                <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-[#142236] sm:rounded-3xl sm:p-6" aria-labelledby="attendance-title"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Fingerprint size={17} className="text-blue-800 dark:text-blue-300" /><h2 id="attendance-title" className="text-sm font-bold text-slate-950 dark:text-slate-100 sm:text-base">Attendance & Biometrics</h2></div><span className="rounded-full bg-blue-50 px-2 py-1 text-[8px] font-bold uppercase text-blue-700 dark:bg-blue-950/40 dark:text-blue-300 sm:text-[9px]">{integration.status}</span></div><div className="mt-3 grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 text-[9px] text-slate-700 dark:bg-slate-900/50 dark:text-slate-300 sm:text-xs"><div><div className="uppercase text-slate-400">Integration source</div><div className="mt-1 font-semibold text-slate-800 dark:text-slate-200">{integration.source}</div></div><div><div className="uppercase text-slate-400">Employees represented</div><div className="mt-1 font-semibold text-slate-800 dark:text-slate-200">{integration.employeesRepresented}</div></div><div><div className="uppercase text-slate-400">Imported events</div><div className="mt-1 font-semibold text-slate-800 dark:text-slate-200">{integration.events}</div></div><div><div className="uppercase text-slate-400">Last event</div><div className="mt-1 font-semibold text-slate-800 dark:text-slate-200">{integration.lastEvent ? new Date(integration.lastEvent).toLocaleString() : 'None'}</div></div></div><div className="mt-3 space-y-2">{attendance.map((a: Attendance) => <div key={a.id} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 px-3 py-2.5 dark:bg-slate-900/50"><div><div className="text-[10px] font-semibold uppercase text-slate-800 dark:text-slate-200 sm:text-sm">{a.event_type}</div><div className="text-[8px] text-slate-500 dark:text-slate-400 sm:text-xs">{a.source}</div></div><div className="text-right text-[10px] font-semibold text-slate-700 dark:text-slate-300 sm:text-sm">{new Date(a.occurred_at).toLocaleString()}</div></div>)}</div><div className="mt-3 flex items-start gap-2 rounded-xl bg-amber-50 p-3 text-[9px] leading-4 text-amber-900 dark:bg-amber-950/35 dark:text-amber-200 sm:text-xs"><ShieldCheck size={14} className="mt-0.5 shrink-0" /> Integration evidence boundary: no physical biometric device is represented as connected. DTR aggregates available attendance evidence without assuming a schedule.</div></section>
            </div>
        </section>
    </PageFrame></AppLayout>;
}
