import { Link, router, useForm } from '@inertiajs/react';
import { Award, CalendarClock, ClipboardCheck, GraduationCap } from 'lucide-react';
import type { FormEvent } from 'react';
import AppLayout from '../../layouts/AppLayout';

type Employee = { id: number; employee_number: string; full_name?: string | null; position_title: string; employment_status: string; contract_end_date?: string | null; department: { name: string; short_name?: string | null } };
type Performance = { id: number; employee: Employee; period_start: string; period_end: string; rating?: string | null; rating_scale?: string | null; status: string; summary?: string | null };
type Development = { id: number; employee: Employee; record_type: string; title: string; provider?: string | null; reference_no?: string | null; attained_at?: string | null; expires_at?: string | null; status: string };
type Summary = { performance: number; development: number; expiringDevelopment: number; contractsDue: number };

export default function Development({ employees, performanceRecords, developmentRecords, summary }: { employees: Employee[]; performanceRecords: Performance[]; developmentRecords: Development[]; summary: Summary }) {
    const performance = useForm({ employee_id: employees[0]?.id ?? '', period_start: '', period_end: '', rating: '', rating_scale: '5-point', status: 'recorded', summary: '', reviewed: false });
    const development = useForm({ employee_id: employees[0]?.id ?? '', record_type: 'training', title: '', provider: '', reference_no: '', attained_at: '', expires_at: '', status: 'active', notes: '' });

    const submitPerformance = (event: FormEvent) => {
        event.preventDefault();
        if (!performance.data.employee_id) return;
        performance.post(`/hris/admin/development/employees/${performance.data.employee_id}/performance`, { preserveScroll: true, onSuccess: () => performance.reset('period_start', 'period_end', 'rating', 'summary') });
    };

    const submitDevelopment = (event: FormEvent) => {
        event.preventDefault();
        if (!development.data.employee_id) return;
        development.post(`/hris/admin/development/employees/${development.data.employee_id}/records`, { preserveScroll: true, onSuccess: () => development.reset('title', 'provider', 'reference_no', 'attained_at', 'expires_at', 'notes') });
    };

    return <AppLayout title="Performance & Development"><div className="mx-auto max-w-7xl space-y-6">
        <section className="rounded-3xl bg-[#0b2852] p-7 text-white"><div className="text-xs font-bold uppercase tracking-[0.18em] text-blue-200">HRIS governed records</div><h1 className="mt-2 text-3xl font-bold">Performance, Training & Eligibility</h1><p className="mt-2 max-w-3xl text-sm text-blue-100">Records here are part of the internal employee lifecycle. Expiring contracts and credentials publish controlled calendar and notification reminders without automatically changing employment status.</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => router.post('/hris/admin/development/sync-expiries')} className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-[#0b2852]">Synchronize expiry alerts</button><Link href="/hris/admin" className="rounded-xl border border-white/25 bg-white/10 px-4 py-2.5 text-sm font-semibold text-white">Back to HR Administration</Link></div></section>

        <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[
            ['Performance records', summary.performance, ClipboardCheck],
            ['Development records', summary.development, GraduationCap],
            ['Credentials due ≤120d', summary.expiringDevelopment, Award],
            ['Contracts due ≤120d', summary.contractsDue, CalendarClock],
        ].map(([label, count, Icon]: any) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon size={18} className="text-blue-800" /><div className="mt-3 text-2xl font-bold text-slate-950">{count}</div><div className="mt-1 text-xs text-slate-500">{label}</div></div>)}</section>

        <section className="grid gap-6 xl:grid-cols-2">
            <form onSubmit={submitPerformance} className="space-y-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold text-slate-950">Record performance evidence</h2><select value={performance.data.employee_id} onChange={(e) => performance.setData('employee_id', Number(e.target.value))} className="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm">{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.employee_number} · {employee.full_name}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><input type="date" value={performance.data.period_start} onChange={(e) => performance.setData('period_start', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" required /><input type="date" value={performance.data.period_end} onChange={(e) => performance.setData('period_end', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" required /></div><div className="grid gap-3 sm:grid-cols-2"><input placeholder="Rating" type="number" step="0.001" value={performance.data.rating} onChange={(e) => performance.setData('rating', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><input placeholder="Scale e.g. 5-point" value={performance.data.rating_scale} onChange={(e) => performance.setData('rating_scale', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /></div><textarea rows={3} placeholder="Performance summary" value={performance.data.summary} onChange={(e) => performance.setData('summary', e.target.value)} className="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><button disabled={performance.processing} className="rounded-xl bg-[#0b2852] px-4 py-2.5 text-sm font-semibold text-white">Save performance record</button></form>

            <form onSubmit={submitDevelopment} className="space-y-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold text-slate-950">Record training / competency / eligibility</h2><select value={development.data.employee_id} onChange={(e) => development.setData('employee_id', Number(e.target.value))} className="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm">{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.employee_number} · {employee.full_name}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><select value={development.data.record_type} onChange={(e) => development.setData('record_type', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="training">Training</option><option value="certification">Certification</option><option value="competency">Competency</option><option value="eligibility">Eligibility</option></select><input placeholder="Title" value={development.data.title} onChange={(e) => development.setData('title', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" required /></div><div className="grid gap-3 sm:grid-cols-2"><input placeholder="Provider / issuer" value={development.data.provider} onChange={(e) => development.setData('provider', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><input placeholder="Reference number" value={development.data.reference_no} onChange={(e) => development.setData('reference_no', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">Attained<input type="date" value={development.data.attained_at} onChange={(e) => development.setData('attained_at', e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm text-slate-900" /></label><label className="text-xs text-slate-500">Expires<input type="date" value={development.data.expires_at} onChange={(e) => development.setData('expires_at', e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm text-slate-900" /></label></div><button disabled={development.processing} className="rounded-xl bg-[#0b2852] px-4 py-2.5 text-sm font-semibold text-white">Save development record</button></form>
        </section>

        <section className="grid gap-6 xl:grid-cols-2"><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-4 font-bold">Recent performance</div><div className="max-h-[500px] divide-y divide-slate-100 overflow-auto">{performanceRecords.map((record) => <div key={record.id} className="px-6 py-4"><div className="font-semibold text-slate-950">{record.employee.full_name}</div><div className="mt-1 text-xs text-slate-500">{new Date(record.period_start).toLocaleDateString()} – {new Date(record.period_end).toLocaleDateString()} · {record.rating || 'No numeric rating'} {record.rating_scale || ''}</div><div className="mt-1 text-xs font-semibold uppercase text-blue-700">{record.status}</div></div>)}</div></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-4 font-bold">Development & eligibility records</div><div className="max-h-[500px] divide-y divide-slate-100 overflow-auto">{developmentRecords.map((record) => <div key={record.id} className="px-6 py-4"><div className="text-[10px] font-bold uppercase text-blue-700">{record.record_type}</div><div className="mt-1 font-semibold text-slate-950">{record.title}</div><div className="mt-1 text-xs text-slate-500">{record.employee.full_name}{record.provider ? ` · ${record.provider}` : ''}{record.expires_at ? ` · expires ${new Date(record.expires_at).toLocaleDateString()}` : ''}</div></div>)}</div></div></section>
    </div></AppLayout>;
}
