import { Link, useForm } from '@inertiajs/react';
import { FileHeart, LockKeyhole, ShieldCheck } from 'lucide-react';
import type { FormEvent } from 'react';
import AppLayout from '../../layouts/AppLayout';

type Employee = { id: number; employee_number: string; full_name?: string | null; position_title: string; department: { name: string; short_name?: string | null } };
type RecordItem = { id: number; record_type: string; title: string; issued_at?: string | null; valid_until?: string | null; status: string; summary?: string | null; restriction_notes?: string | null; creator?: string | null; created_at?: string | null };

export default function HealthVault({ employee, records, canManage }: { employee: Employee; records: RecordItem[]; canManage: boolean }) {
    const form = useForm({ record_type: 'fit_to_work', title: '', issued_at: '', valid_until: '', status: 'active', summary: '', restriction_notes: '' });
    const submit = (event: FormEvent) => {
        event.preventDefault();
        form.post(`/hris/health/${employee.id}`, { preserveScroll: true, onSuccess: () => form.reset('title', 'issued_at', 'valid_until', 'summary', 'restriction_notes') });
    };

    return <AppLayout title="Restricted Health Vault"><div className="mx-auto max-w-5xl space-y-6">
        <section className="rounded-3xl border border-rose-200 bg-rose-950 p-7 text-white"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-rose-200"><LockKeyhole size={16} /> Restricted employment record</div><h1 className="mt-2 text-3xl font-bold">{employee.full_name} · Health Vault</h1><p className="mt-2 text-sm text-rose-100">{employee.employee_number} · {employee.position_title} · {employee.department.short_name || employee.department.name}</p><div className="mt-5 rounded-2xl border border-white/15 bg-white/10 p-4 text-sm leading-6 text-rose-50">This vault is limited to employment and occupational-health evidence such as medical certificates, fit-to-work status, accommodations, and authorized clearances. It is not an RHU patient chart and does not contain municipal health-service consultation history.</div></section>

        {canManage && <form onSubmit={submit} className="space-y-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><FileHeart size={19} className="text-rose-800" /><h2 className="font-bold text-slate-950">Add governed health evidence</h2></div><div className="grid gap-3 sm:grid-cols-2"><select value={form.data.record_type} onChange={(e) => form.setData('record_type', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="medical_certificate">Medical certificate</option><option value="fit_to_work">Fit to work</option><option value="occupational_exam">Occupational examination</option><option value="accommodation">Authorized accommodation</option><option value="vaccination">Vaccination record</option><option value="health_clearance">Health clearance</option><option value="other">Other employment-health evidence</option></select><input required placeholder="Record title" value={form.data.title} onChange={(e) => form.setData('title', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">Issued<input type="date" value={form.data.issued_at} onChange={(e) => form.setData('issued_at', e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm text-slate-900" /></label><label className="text-xs text-slate-500">Valid until<input type="date" value={form.data.valid_until} onChange={(e) => form.setData('valid_until', e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm text-slate-900" /></label></div><textarea rows={3} placeholder="Employment-relevant summary" value={form.data.summary} onChange={(e) => form.setData('summary', e.target.value)} className="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><textarea rows={3} placeholder="Authorized restriction / accommodation notes" value={form.data.restriction_notes} onChange={(e) => form.setData('restriction_notes', e.target.value)} className="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><button disabled={form.processing} className="rounded-xl bg-rose-900 px-4 py-2.5 text-sm font-semibold text-white">Save restricted record</button></form>}

        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck size={19} className="text-rose-800" /><h2 className="font-bold text-slate-950">Authorized record view</h2></div><div className="mt-4 space-y-3">{records.map((record) => <article key={record.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-[10px] font-bold uppercase tracking-wide text-rose-700">{record.record_type.replaceAll('_', ' ')}</div><div className="mt-1 font-semibold text-slate-950">{record.title}</div></div><span className="w-fit rounded-full bg-slate-100 px-2.5 py-1 text-[9px] font-bold uppercase text-slate-700">{record.status}</span></div><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><div className="text-xs text-slate-400">Issued / valid until</div><div className="mt-1 text-slate-700">{record.issued_at || 'Not recorded'} · {record.valid_until || 'No expiry recorded'}</div></div><div><div className="text-xs text-slate-400">Recorded by</div><div className="mt-1 text-slate-700">{record.creator || 'Authorized personnel'}</div></div></div>{record.summary && <div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-700"><div className="text-[10px] font-bold uppercase text-slate-400">Employment-relevant summary</div><div className="mt-1">{record.summary}</div></div>}{record.restriction_notes && <div className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><div className="text-[10px] font-bold uppercase text-amber-700">Authorized restriction / accommodation</div><div className="mt-1">{record.restriction_notes}</div></div>}</article>)}{records.length === 0 && <div className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">No employment/occupational-health records are present in this restricted vault.</div>}</div></section>

        <div className="flex justify-end"><Link href={`/employees/${employee.id}`} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700">Return to employee profile</Link></div>
    </div></AppLayout>;
}
