import { router, useForm } from '@inertiajs/react';
import { KeyRound, ShieldCheck, UserRoundCog } from 'lucide-react';
import type { FormEvent } from 'react';
import AppLayout from '../../layouts/AppLayout';

type User = { id: number; name: string; email: string; role: string };
type Employee = { id: number; employee_number: string; full_name?: string | null; position_title: string };
type Grant = { id: number; user: User; employee?: Employee | null; can_view: boolean; can_manage: boolean; purpose: string; granted_at: string; expires_at?: string | null; revoked_at?: string | null; granter?: { name: string } | null };

export default function HealthAccess({ grants, users, employees }: { grants: Grant[]; users: User[]; employees: Employee[] }) {
    const form = useForm({ user_id: users[0]?.id ?? '', employee_id: '', can_manage: false, purpose: '', expires_at: '' });
    const submit = (event: FormEvent) => {
        event.preventDefault();
        form.post('/hris/health-access', { preserveScroll: true, onSuccess: () => form.reset('purpose', 'expires_at') });
    };

    return <AppLayout title="Health Vault Access"><div className="mx-auto max-w-6xl space-y-6">
        <section className="rounded-3xl bg-[#0b2852] p-7 text-white"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-blue-200"><ShieldCheck size={16} /> Explicit authorization boundary</div><h1 className="mt-2 text-3xl font-bold">Employee Health Vault Access Policy</h1><p className="mt-2 max-w-3xl text-sm text-blue-100">System administration does not automatically grant medical-content access. This surface manages explicit, purpose-bound, revocable access to employment and occupational-health records. RHU patient clinical records remain outside this HRIS boundary.</p></section>

        <form onSubmit={submit} className="space-y-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><UserRoundCog size={19} className="text-blue-800" /><h2 className="font-bold text-slate-950">Grant restricted access</h2></div><div className="grid gap-3 md:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Authorized user<select value={form.data.user_id} onChange={(e) => form.setData('user_id', Number(e.target.value))} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm text-slate-900">{users.map((user) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Vault scope<select value={form.data.employee_id} onChange={(e) => form.setData('employee_id', e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm text-slate-900"><option value="">All employee health vaults</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.employee_number} · {employee.full_name}</option>)}</select></label></div><label className="block text-xs font-semibold text-slate-600">Purpose / authority<textarea required rows={3} value={form.data.purpose} onChange={(e) => form.setData('purpose', e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm text-slate-900" placeholder="State the authorized employment/occupational-health purpose." /></label><div className="grid gap-3 md:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Expires at<input type="datetime-local" value={form.data.expires_at} onChange={(e) => form.setData('expires_at', e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm text-slate-900" /></label><label className="flex items-center gap-3 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-800"><input type="checkbox" checked={form.data.can_manage} onChange={(e) => form.setData('can_manage', e.target.checked)} />Allow adding governed health records</label></div><button disabled={form.processing} className="rounded-xl bg-[#0b2852] px-4 py-2.5 text-sm font-semibold text-white">Record explicit grant</button></form>

        <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-5"><div className="flex items-center gap-2"><KeyRound size={18} className="text-blue-800" /><h2 className="font-bold text-slate-950">Access grant ledger</h2></div><p className="mt-1 text-xs text-slate-500">Grant metadata is auditable; health-record content is not shown here.</p></div><div className="divide-y divide-slate-100">{grants.map((grant) => <div key={grant.id} className="flex flex-col gap-3 px-6 py-4 md:flex-row md:items-start md:justify-between"><div><div className="font-semibold text-slate-950">{grant.user.name} · {grant.user.email}</div><div className="mt-1 text-xs text-slate-500">Scope: {grant.employee ? `${grant.employee.employee_number} · ${grant.employee.full_name}` : 'All employee health vaults'}</div><div className="mt-1 text-xs text-slate-500">Purpose: {grant.purpose}</div><div className="mt-1 text-[10px] uppercase text-slate-400">{grant.can_manage ? 'View + manage' : 'View only'} · granted {new Date(grant.granted_at).toLocaleString()}{grant.expires_at ? ` · expires ${new Date(grant.expires_at).toLocaleString()}` : ''}</div></div>{grant.revoked_at ? <span className="w-fit rounded-full bg-slate-100 px-3 py-1 text-[10px] font-bold uppercase text-slate-600">Revoked</span> : <button onClick={() => router.post(`/hris/health-access/${grant.id}/revoke`)} className="w-fit rounded-xl border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-700">Revoke</button>}</div>)}{grants.length === 0 && <div className="px-6 py-10 text-center text-sm text-slate-500">No explicit health-vault access grants recorded.</div>}</div></section>
    </div></AppLayout>;
}
