import { Link, router } from '@inertiajs/react';
import { Building2, Search, UserRoundCheck, UsersRound } from 'lucide-react';
import { FormEvent, useState } from 'react';
import PageFrame from '../../components/PageFrame';
import PageHeader from '../../components/PageHeader';
import AppLayout from '../../layouts/AppLayout';

type Department = { code: string; name: string; short_name?: string };
type Employee = { id: number; employee_number: string; full_name?: string; work_email?: string; position_title: string; employment_status: string; user_id?: number | null; department: Department };
type PaginatedEmployees = { data: Employee[]; current_page: number; last_page: number; per_page: number; total: number; prev_page_url?: string | null; next_page_url?: string | null };
type Props = { employees: PaginatedEmployees; departments: Department[]; filters: { q: string; department: string }; summary: { employees: number; portalAccounts: number; featuredLogins: number; offices: number } };

export default function EmployeeDirectory({ employees, departments, filters, summary }: Props) {
    const [q, setQ] = useState(filters.q || '');
    const [department, setDepartment] = useState(filters.department || '');
    const submit = (event: FormEvent) => { event.preventDefault(); router.get('/employees', { q, department }, { preserveState: true, preserveScroll: true, replace: true }); };
    const reset = () => { setQ(''); setDepartment(''); router.get('/employees', {}, { preserveState: true, replace: true }); };
    const summaryCard = 'min-w-0 rounded-xl border border-slate-200 bg-white p-3 shadow-sm transition-colors dark:border-slate-700 dark:bg-[#142236] sm:rounded-2xl sm:p-5';

    return <AppLayout title="Employee Directory"><PageFrame>
        <PageHeader eyebrow="Municipal workforce" title="Employee Directory" description="Search active municipal personnel by name, employee number, office, email, or position and open employee profiles available within your current access." icon={UsersRound} aside={<div className="inline-flex items-center gap-2 rounded-xl bg-blue-50 px-3 py-2 text-[11px] font-semibold text-blue-800 dark:bg-blue-950/40 dark:text-blue-200 sm:text-xs"><UserRoundCheck size={15} /> {summary.portalAccounts} portal identities</div>} />

        <section aria-label="Employee directory summary" className="grid grid-cols-3 gap-2.5 sm:gap-4">
            <div className={summaryCard}><UsersRound size={17} className="text-blue-800 dark:text-blue-300"/><div className="mt-2 text-xl font-bold text-slate-950 dark:text-slate-100 sm:text-3xl">{summary.employees}</div><div className="mt-0.5 text-[9px] uppercase tracking-wide text-slate-500 dark:text-slate-400 sm:text-xs">Employees</div></div>
            <div className={summaryCard}><Building2 size={17} className="text-blue-800 dark:text-blue-300"/><div className="mt-2 text-xl font-bold text-slate-950 dark:text-slate-100 sm:text-3xl">{summary.offices}</div><div className="mt-0.5 text-[9px] uppercase tracking-wide text-slate-500 dark:text-slate-400 sm:text-xs">Offices</div></div>
            <div className={summaryCard}><UserRoundCheck size={17} className="text-blue-800 dark:text-blue-300"/><div className="mt-2 text-xl font-bold text-slate-950 dark:text-slate-100 sm:text-3xl">{summary.portalAccounts}</div><div className="mt-0.5 text-[9px] uppercase tracking-wide text-slate-500 dark:text-slate-400 sm:text-xs">Portal identities</div></div>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white shadow-sm transition-colors dark:border-slate-700 dark:bg-[#142236] sm:rounded-3xl"><form onSubmit={submit} aria-label="Employee directory filters" className="grid gap-2.5 border-b border-slate-100 p-3 dark:border-slate-700 sm:grid-cols-[1fr_280px_auto_auto] sm:p-5"><label className="relative"><span className="sr-only">Search employees</span><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={(e)=>setQ(e.target.value)} placeholder="Search name, ID, email, or position" className="w-full rounded-xl border border-slate-300 bg-white py-2.5 pl-9 pr-3 text-[12px] text-slate-900 outline-none focus:border-blue-500 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-100 sm:text-sm"/></label><label className="sr-only" htmlFor="employee-office-filter">Office</label><select id="employee-office-filter" value={department} onChange={(e)=>setDepartment(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-[12px] text-slate-900 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-100 sm:text-sm"><option value="">All offices</option>{departments.map((office)=><option key={office.code} value={office.code}>{office.short_name||office.name}</option>)}</select><button className="rounded-xl bg-[#0b2852] px-4 py-2.5 text-[12px] font-semibold text-white sm:text-sm">Search</button><button type="button" onClick={reset} className="rounded-xl border border-slate-300 px-4 py-2.5 text-[12px] font-semibold text-slate-700 dark:border-slate-600 dark:text-slate-200 sm:text-sm">Reset</button></form>

            <div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-500 dark:bg-slate-900/40 dark:text-slate-400"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Office</th><th className="px-5 py-3">Position</th><th className="px-5 py-3">Portal</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-700">{employees.data.map((employee)=><tr key={employee.id} className="hover:bg-slate-50/70 dark:hover:bg-slate-800/50"><td className="px-5 py-4"><Link href={`/employees/${employee.id}`} className="font-semibold text-slate-950 hover:text-blue-800 dark:text-slate-100 dark:hover:text-blue-300">{employee.full_name||'Employee record'}</Link><div className="mt-0.5 break-words text-xs text-slate-500 dark:text-slate-400">{employee.employee_number}{employee.work_email?` · ${employee.work_email}`:''}</div></td><td className="px-5 py-4 text-slate-700 dark:text-slate-300">{employee.department.short_name||employee.department.name}</td><td className="px-5 py-4 text-slate-700 dark:text-slate-300">{employee.position_title}</td><td className="px-5 py-4"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold uppercase text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300">Enabled</span></td></tr>)}</tbody></table></div>
            <div className="divide-y divide-slate-100 dark:divide-slate-700 md:hidden">{employees.data.map((employee)=><article key={employee.id} className="min-w-0 p-3.5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><Link href={`/employees/${employee.id}`} className="break-words text-[13px] font-semibold text-slate-950 hover:text-blue-800 dark:text-slate-100 dark:hover:text-blue-300">{employee.full_name||'Employee record'}</Link><div className="mt-0.5 break-all text-[9px] font-semibold text-blue-700 dark:text-blue-300">{employee.employee_number}</div></div><span className="shrink-0 rounded-full bg-emerald-50 px-2 py-1 text-[8px] font-bold uppercase text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300">Portal</span></div><div className="mt-2 break-words text-[11px] text-slate-600 dark:text-slate-300">{employee.department.short_name||employee.department.name}</div><div className="mt-0.5 break-words text-[11px] text-slate-500 dark:text-slate-400">{employee.position_title}</div>{employee.work_email&&<div className="mt-1 break-all text-[9px] text-slate-400">{employee.work_email}</div>}</article>)}</div>
            {employees.data.length===0&&<div className="px-5 py-10 text-center text-sm text-slate-500 dark:text-slate-400">No employees match the current filters.</div>}
            <div className="flex items-center justify-between gap-3 border-t border-slate-100 px-3 py-3 text-[10px] text-slate-500 dark:border-slate-700 dark:text-slate-400 sm:px-5 sm:text-xs"><div>Showing {employees.data.length} of {employees.total} matching employees</div><div className="flex gap-2">{employees.prev_page_url?<Link href={employees.prev_page_url} preserveScroll preserveState className="rounded-lg border border-slate-300 px-3 py-1.5 font-semibold text-slate-700 dark:border-slate-600 dark:text-slate-200">Previous</Link>:null}{employees.next_page_url?<Link href={employees.next_page_url} preserveScroll preserveState className="rounded-lg border border-slate-300 px-3 py-1.5 font-semibold text-slate-700 dark:border-slate-600 dark:text-slate-200">Next</Link>:null}</div></div>
        </section>
    </PageFrame></AppLayout>;
}
