import { Link, router } from '@inertiajs/react';
import { Building2, Search, UserRoundCheck, UsersRound } from 'lucide-react';
import { FormEvent, useState } from 'react';
import PageFrame from '../../components/PageFrame';
import PageHeader from '../../components/PageHeader';
import AppLayout from '../../layouts/AppLayout';

type Department = { code: string; name: string; short_name?: string };
type Employee = { id: number; employee_number: string; full_name?: string; work_email?: string; position_title: string; employment_status: string; user_id?: number | null; department: Department };
type PaginatedEmployees = { data: Employee[]; current_page: number; last_page: number; per_page: number; total: number; prev_page_url?: string | null; next_page_url?: string | null };
type Props = { employees: PaginatedEmployees; departments: Department[]; filters: { q: string; department: string }; summary: { employees: number; portalAccounts: number; featuredLogins: number; offices: number } };

export default function EmployeeDirectory({ employees, departments, filters, summary }: Props) {
    const [q, setQ] = useState(filters.q || '');
    const [department, setDepartment] = useState(filters.department || '');
    const submit = (event: FormEvent) => { event.preventDefault(); router.get('/employees', { q, department }, { preserveState: true, preserveScroll: true, replace: true }); };
    const reset = () => { setQ(''); setDepartment(''); router.get('/employees', {}, { preserveState: true, replace: true }); };
    const summaryItems = [['Employees', summary.employees, UsersRound], ['Municipal offices', summary.offices, Building2], ['Portal accounts', summary.portalAccounts, UserRoundCheck]] as const;

    return <AppLayout title="Employee Directory"><PageFrame>
        <PageHeader eyebrow="Municipal organization" title="Employee Directory" description="Search municipal personnel by name, employee number, office, work email, or position. The directory exposes work context only and does not include private personal contact information." icon={UsersRound} />
        <section className="grid grid-cols-3 gap-2" aria-label="Employee directory summary">{summaryItems.map(([label, value, Icon]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-[#142236] sm:p-4"><Icon size={17} className="text-blue-800 dark:text-blue-300" /><div className="mt-2 text-xl font-bold text-slate-950 dark:text-slate-100 sm:text-2xl">{value}</div><div className="mt-0.5 text-[10px] font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400 sm:text-xs">{label}</div></div>)}</section>
        <section className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-[#142236]">
            <form onSubmit={submit} aria-label="Employee directory filters" className="grid gap-2 border-b border-slate-100 p-3 dark:border-slate-700 sm:grid-cols-[1fr_280px_auto_auto] sm:p-4"><label className="relative"><span className="sr-only">Search employees</span><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={(event) => setQ(event.target.value)} placeholder="Search name, employee number, work email, or position" className="min-h-10 w-full rounded-lg border border-slate-300 bg-white pl-9 pr-3 text-sm text-slate-900 outline-none focus:border-blue-700 focus:ring-2 focus:ring-blue-700/20 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-100" /></label><select aria-label="Office" value={department} onChange={(event) => setDepartment(event.target.value)} className="min-h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm dark:border-slate-600 dark:bg-slate-900 dark:text-slate-100"><option value="">All offices</option>{departments.map((office) => <option key={office.code} value={office.code}>{office.short_name || office.name}</option>)}</select><button className="min-h-10 rounded-lg bg-[#0b2852] px-4 text-sm font-semibold text-white focus:outline-none focus:ring-2 focus:ring-blue-700/30">Search</button><button type="button" onClick={reset} className="min-h-10 rounded-lg border border-slate-300 px-4 text-sm font-semibold text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-700/30 dark:border-slate-600 dark:text-slate-200">Reset</button></form>
            <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500 dark:bg-slate-900/40 dark:text-slate-400"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Office</th><th className="px-4 py-3">Position</th><th className="px-4 py-3">Portal account</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-700">{employees.data.map((employee) => <tr key={employee.id} className="hover:bg-slate-50/70 dark:hover:bg-slate-800/50"><td className="px-4 py-3"><Link href={`/employees/${employee.id}`} className="font-semibold text-slate-950 hover:text-blue-800 dark:text-slate-100 dark:hover:text-blue-300">{employee.full_name || 'Employee record'}</Link><div className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{employee.employee_number}{employee.work_email ? ` · ${employee.work_email}` : ''}</div></td><td className="px-4 py-3 text-slate-700 dark:text-slate-300">{employee.department.short_name || employee.department.name}</td><td className="px-4 py-3 text-slate-700 dark:text-slate-300">{employee.position_title}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${employee.user_id ? 'bg-emerald-50 text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300'}`}>{employee.user_id ? 'Enabled' : 'Not linked'}</span></td></tr>)}</tbody></table></div>
            {employees.data.length === 0 && <div className="px-5 py-10 text-center text-sm text-slate-500 dark:text-slate-400">No employees match the current filters.</div>}
            <div className="flex items-center justify-between gap-3 border-t border-slate-100 px-4 py-3 text-xs text-slate-500 dark:border-slate-700 dark:text-slate-400"><div>Showing {employees.data.length} of {employees.total} matching employees</div><div className="flex gap-2">{employees.prev_page_url && <Link href={employees.prev_page_url} preserveScroll preserveState className="rounded-lg border border-slate-300 px-3 py-1.5 font-semibold text-slate-700 dark:border-slate-600 dark:text-slate-200">Previous</Link>}{employees.next_page_url && <Link href={employees.next_page_url} preserveScroll preserveState className="rounded-lg border border-slate-300 px-3 py-1.5 font-semibold text-slate-700 dark:border-slate-600 dark:text-slate-200">Next</Link>}</div></div>
        </section>
    </PageFrame></AppLayout>;
}
