import { router } from '@inertiajs/react';
import AppLayout from '../../../layouts/AppLayout';

type Department = { id: number; code: string; name: string; short_name?: string | null };
type Task = { id: number; task_key: string; title: string; is_required: boolean; status: string; due_at?: string | null; notes?: string | null; owner_department?: Department | null; completer?: { id: number; name: string } | null; completed_at?: string | null };
type Props = { case: { id: number; separation_type: string; effective_date: string; status: string; reason?: string | null; employee: { id: number; employee_number: string; full_name: string; position_title: string; employment_status: string; department?: Department }; tasks: Task[] }; summary: { required: number; completed: number; openRequired: number } };

export default function OffboardingShow({ case: offboarding, summary }: Props) {
    const complete = (task: Task) => router.post(`/hris/admin/offboarding/tasks/${task.id}/complete`, {}, { preserveScroll: true });
    const finalize = () => router.post(`/hris/admin/offboarding/${offboarding.id}/finalize`, {}, { preserveScroll: true });
    return <AppLayout title="Offboarding Clearance"><div className="mx-auto max-w-5xl space-y-6">
        <section className="rounded-3xl bg-[#0b2852] p-6 text-white sm:p-8"><div className="text-xs font-bold uppercase tracking-[0.2em] text-blue-200">Employee separation</div><h1 className="mt-3 text-3xl font-bold">{offboarding.employee.full_name}</h1><p className="mt-2 text-sm text-blue-100">{offboarding.employee.employee_number} · {offboarding.employee.position_title} · {offboarding.employee.department?.short_name || offboarding.employee.department?.name}</p><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-white/10 px-3 py-1.5">{offboarding.separation_type.replaceAll('_', ' ')}</span><span className="rounded-full bg-white/10 px-3 py-1.5">Effective {new Date(offboarding.effective_date).toLocaleDateString()}</span><span className="rounded-full bg-white/10 px-3 py-1.5">{summary.openRequired} open blockers</span></div></section>
        <section className="rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">Clearance checklist</h2><p className="mt-1 text-xs text-slate-500">Mandatory operational blockers are verified against live work/property state where applicable.</p></div><div className="divide-y divide-slate-100">{offboarding.tasks.map(task => <div key={task.id} className="p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="font-semibold text-slate-950">{task.title}</div><div className="mt-1 text-xs text-slate-500">{task.owner_department?.short_name || task.owner_department?.name || 'System managed'} · {task.is_required ? 'Required' : 'Not required'}</div>{task.notes && <div className="mt-2 text-xs text-slate-600">{task.notes}</div>}</div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[9px] font-bold uppercase text-slate-700">{task.status.replaceAll('_', ' ')}</span>{!['completed','not_required','waived','system_pending'].includes(task.status) && <button onClick={() => complete(task)} className="rounded-lg bg-blue-700 px-3 py-1.5 text-xs font-semibold text-white">Complete</button>}</div></div></div>)}</div></section>
        {offboarding.status !== 'completed' && <section className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><div className="font-bold text-amber-950">Finalization gate</div><p className="mt-2 text-sm leading-6 text-amber-900">Finalization re-checks open assigned work and outstanding property, requires all mandatory manual clearances, deactivates the linked portal identity, and archives employment. Historical workflow, HR, payroll, DTR, property and audit records are retained.</p><button disabled={summary.openRequired > 1} onClick={finalize} className="mt-4 rounded-xl bg-amber-900 px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">Finalize offboarding</button></section>}
    </div></AppLayout>;
}
