import { Link, useForm } from '@inertiajs/react';
import { CheckCircle2, Play, Send, ShieldCheck } from 'lucide-react';
import { type FormEvent, type ReactNode } from 'react';
import EvidenceFields from '../documents/EvidenceFields';

export type CorrespondenceCapabilities = { canRegister:boolean; canClassify:boolean; canRoute:boolean; canAct:boolean };
export type CorrespondenceRouteOption = { id:number; code:string; name:string; shortName?:string|null };
type Props={publicId:string;lifecycleState:string;capabilities:CorrespondenceCapabilities;routeOptions:CorrespondenceRouteOption[];linkedWorkflowUrl?:string|null};
const inputClass='mt-1.5 min-h-10 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-700 focus:ring-2 focus:ring-blue-700/20 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-100';
const primaryClass='inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-[#0b2852] px-4 py-2.5 text-sm font-bold text-white focus:outline-none focus:ring-2 focus:ring-blue-700/30 disabled:cursor-not-allowed disabled:opacity-50';
const errorFor=(errors:unknown,key:string)=>(errors as Record<string,string|undefined>)[key];
function ErrorText({children}:{children?:string}){return children?<div className="mt-1 text-xs font-medium text-rose-700 dark:text-rose-300">{children}</div>:null}
function ActionShell({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="rounded-xl border border-blue-200 bg-blue-50/50 p-4 dark:border-blue-900 dark:bg-blue-950/20 sm:p-5"><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-blue-700 dark:text-blue-300">Required action</div><h2 className="mt-1.5 text-base font-bold text-slate-950 dark:text-slate-100 sm:text-lg">{title}</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-600 dark:text-slate-300 sm:text-sm">{description}</p><div className="mt-4">{children}</div></section>}
export default function CorrespondenceActionPanel({publicId,lifecycleState,capabilities,routeOptions,linkedWorkflowUrl}:Props){
 const registerForm=useForm<{evidence:File[]}>({evidence:[]});
 const classifyForm=useForm<{classification:string;remarks:string;evidence:File[]}>({classification:'internal',remarks:'',evidence:[]});
 const routeForm=useForm<{target_department_id:number|'';priority:'normal'|'high'|'urgent';due_at:string;remarks:string;evidence:File[]}>({target_department_id:routeOptions[0]?.id??'',priority:'normal',due_at:'',remarks:'',evidence:[]});
 const actForm=useForm<{remarks:string;evidence:File[]}>({remarks:'',evidence:[]});
 const submitRegister=()=>{if(!window.confirm('Register this correspondence and assign its official municipal reference?'))return;registerForm.post(`/correspondence/${publicId}/workspace/register`,{preserveScroll:true,forceFormData:true})};
 const submitClassify=(e:FormEvent)=>{e.preventDefault();classifyForm.post(`/correspondence/${publicId}/workspace/classify`,{preserveScroll:true,forceFormData:true})};
 const submitRoute=(e:FormEvent)=>{e.preventDefault();routeForm.post(`/correspondence/${publicId}/workspace/route`,{preserveScroll:true,forceFormData:true})};
 const submitAct=(e:FormEvent)=>{e.preventDefault();actForm.post(`/correspondence/${publicId}/workspace/act`,{preserveScroll:true,forceFormData:true})};
 if(capabilities.canRegister)return <ActionShell title="Register correspondence" description="Registration assigns the official municipal correspondence reference and moves this record into the municipal register."><div className="space-y-3"><EvidenceFields files={registerForm.data.evidence} onChange={files=>registerForm.setData('evidence',files)} errors={registerForm.errors as Record<string,string|undefined>} disabled={registerForm.processing} label="Registration evidence"/><ErrorText>{errorFor(registerForm.errors,'correspondence')}</ErrorText><button type="button" disabled={registerForm.processing} onClick={submitRegister} className={primaryClass}><CheckCircle2 size={16}/>{registerForm.processing?'Registering…':'Register correspondence'}</button></div></ActionShell>;
 if(capabilities.canClassify){const sensitive=['confidential','restricted'].includes(classifyForm.data.classification);return <ActionShell title="Classify correspondence" description="Choose the municipal access classification for this registered correspondence."><form onSubmit={submitClassify} className="space-y-3"><label className="block text-sm font-semibold text-slate-700 dark:text-slate-200">Classification<select value={classifyForm.data.classification} onChange={e=>classifyForm.setData('classification',e.target.value)} className={inputClass}><option value="public">Public</option><option value="internal">Internal</option><option value="confidential">Confidential</option><option value="restricted">Restricted</option></select><ErrorText>{classifyForm.errors.classification}</ErrorText></label>{sensitive&&<div className="flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-800 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><ShieldCheck size={14} className="mt-0.5 shrink-0"/>This classification limits who can view and act on the correspondence and linked evidence.</div>}<label className="block text-sm font-semibold text-slate-700 dark:text-slate-200">Remarks <span className="font-normal text-slate-400">optional</span><textarea value={classifyForm.data.remarks} onChange={e=>classifyForm.setData('remarks',e.target.value)} rows={3} className={inputClass} placeholder="Classification note"/><ErrorText>{classifyForm.errors.remarks}</ErrorText></label><EvidenceFields files={classifyForm.data.evidence} onChange={files=>classifyForm.setData('evidence',files)} errors={classifyForm.errors as Record<string,string|undefined>} disabled={classifyForm.processing} label="Classification evidence"/><ErrorText>{errorFor(classifyForm.errors,'correspondence')}</ErrorText><button disabled={classifyForm.processing} className={primaryClass}>{classifyForm.processing?'Saving…':'Save classification'}</button></form></ActionShell>}
 if(capabilities.canRoute)return <ActionShell title="Route correspondence" description="Send this classified correspondence to the office responsible for the next action."><form onSubmit={submitRoute} className="space-y-3"><label className="block text-sm font-semibold text-slate-700 dark:text-slate-200">Destination office<select value={routeForm.data.target_department_id} onChange={e=>routeForm.setData('target_department_id',e.target.value?Number(e.target.value):'')} className={inputClass}>{routeOptions.length===0&&<option value="">No valid destination available</option>}{routeOptions.map(office=><option key={office.id} value={office.id}>{office.shortName||office.name}</option>)}</select><ErrorText>{routeForm.errors.target_department_id}</ErrorText></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-semibold text-slate-700 dark:text-slate-200">Priority<select value={routeForm.data.priority} onChange={e=>routeForm.setData('priority',e.target.value as 'normal'|'high'|'urgent')} className={inputClass}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><ErrorText>{routeForm.errors.priority}</ErrorText></label><label className="block text-sm font-semibold text-slate-700 dark:text-slate-200">Due date <span className="font-normal text-slate-400">optional</span><input type="date" value={routeForm.data.due_at} onChange={e=>routeForm.setData('due_at',e.target.value)} className={inputClass}/><ErrorText>{routeForm.errors.due_at}</ErrorText></label></div><label className="block text-sm font-semibold text-slate-700 dark:text-slate-200">Remarks <span className="font-normal text-slate-400">optional</span><textarea value={routeForm.data.remarks} onChange={e=>routeForm.setData('remarks',e.target.value)} rows={3} className={inputClass} placeholder="Instructions for the receiving office"/><ErrorText>{routeForm.errors.remarks}</ErrorText></label><EvidenceFields files={routeForm.data.evidence} onChange={files=>routeForm.setData('evidence',files)} errors={routeForm.errors as Record<string,string|undefined>} disabled={routeForm.processing} label="Routing evidence"/><ErrorText>{errorFor(routeForm.errors,'correspondence')}</ErrorText><button disabled={routeForm.processing||routeOptions.length===0} className={primaryClass}><Send size={15}/>{routeForm.processing?'Routing…':'Route correspondence'}</button></form></ActionShell>;
 if(capabilities.canAct)return <ActionShell title="Start action" description="Formally mark that the authorized receiving office or responsible person has begun work on this correspondence."><form onSubmit={submitAct} className="space-y-3"><label className="block text-sm font-semibold text-slate-700 dark:text-slate-200">Remarks <span className="font-normal text-slate-400">optional</span><textarea value={actForm.data.remarks} onChange={e=>actForm.setData('remarks',e.target.value)} rows={3} className={inputClass} placeholder="Initial action note"/></label><EvidenceFields files={actForm.data.evidence} onChange={files=>actForm.setData('evidence',files)} errors={actForm.errors as Record<string,string|undefined>} disabled={actForm.processing} label="Action evidence / photos"/><ErrorText>{errorFor(actForm.errors,'correspondence')||errorFor(actForm.errors,'workflow')}</ErrorText><button disabled={actForm.processing} className={primaryClass}><Play size={15}/>{actForm.processing?'Starting…':'Start action'}</button></form></ActionShell>;
 if(lifecycleState==='routed'&&linkedWorkflowUrl)return <section className="rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/40 sm:p-5"><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400">Next step</div><div className="mt-1.5 text-sm font-bold text-slate-900 dark:text-slate-100 sm:text-base">Prepare the linked workflow for action</div><p className="mt-1 text-xs leading-5 text-slate-600 dark:text-slate-300 sm:text-sm">This correspondence is routed but is not yet actionable. Open the linked workflow to complete the existing assignment or review step.</p><Link href={linkedWorkflowUrl} className="mt-3 inline-flex min-h-9 items-center rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-blue-700/30 dark:border-slate-600 dark:bg-[#142236] dark:text-slate-200">Open linked workflow</Link></section>;
 return null;
}
