import {
    AppWindow,
    BookOpen,
    Building2,
    CalendarClock,
    CalendarDays,
    FileSearch,
    FileText,
    FolderKanban,
    Inbox,
    Landmark,
    LayoutDashboard,
    ListChecks,
    Megaphone,
    MessagesSquare,
    Network,
    Settings,
    UserCog,
    Users,
} from 'lucide-react';
import { portalRoutePlan } from './navigationRoutePlan';
import type { PortalDestination, PortalDestinationKey } from './navigationTypes';

export const portalDestinations: Partial<Record<PortalDestinationKey, PortalDestination>> = {
    home: { key: 'home', label: 'Home', href: portalRoutePlan.home, icon: LayoutDashboard, group: 'home', readiness: 'wired', permission: 'dashboard' },
    myWork: { key: 'myWork', label: 'My Work', href: portalRoutePlan.myWork, icon: FileText, group: 'work', readiness: 'wired', permission: 'transactions' },
    correspondence: { key: 'correspondence', label: 'Correspondence', href: portalRoutePlan.correspondence, icon: Inbox, group: 'work', readiness: 'wired', permission: 'correspondence' },
    records: { key: 'records', label: 'Records', href: portalRoutePlan.records, icon: FileSearch, group: 'work', readiness: 'wired', permission: 'records' },
    memoranda: { key: 'memoranda', label: 'Memoranda', href: portalRoutePlan.memoranda, icon: FileText, group: 'work', readiness: 'wired', permission: 'memoranda' },
    announcements: { key: 'announcements', label: 'Announcements', href: portalRoutePlan.announcements, icon: Megaphone, group: 'work', readiness: 'integration_pending' },
    calendar: { key: 'calendar', label: 'Calendar', href: portalRoutePlan.calendar, icon: CalendarDays, group: 'work', readiness: 'wired' },
    meetings: { key: 'meetings', label: 'Meetings', href: portalRoutePlan.meetings, icon: CalendarClock, group: 'work', readiness: 'integration_pending' },
    messages: { key: 'messages', label: 'Messages', href: portalRoutePlan.messages, icon: MessagesSquare, group: 'work', readiness: 'integration_pending' },
    executiveDepartments: { key: 'executiveDepartments', label: 'Executive Departments', href: portalRoutePlan.executiveDepartments, icon: Building2, group: 'organization', readiness: 'wired', permission: 'departments' },
    employeeDirectory: { key: 'employeeDirectory', label: 'Employee Directory', href: portalRoutePlan.employeeDirectory, icon: Users, group: 'organization', readiness: 'wired' },
    legislative: { key: 'legislative', label: 'Legislative', href: portalRoutePlan.legislative, icon: Landmark, group: 'organization', readiness: 'wired' },
    localSpecialBodies: { key: 'localSpecialBodies', label: 'Local Special Bodies', href: portalRoutePlan.localSpecialBodies, icon: Network, group: 'organization', readiness: 'integration_pending' },
    developmentPlans: { key: 'developmentPlans', label: 'Development Plans', href: portalRoutePlan.developmentPlans, icon: BookOpen, group: 'planning', readiness: 'integration_pending' },
    ppas: { key: 'ppas', label: 'PPAs', href: portalRoutePlan.ppas, icon: ListChecks, group: 'planning', readiness: 'integration_pending' },
    projectMonitoring: { key: 'projectMonitoring', label: 'Project Monitoring', href: portalRoutePlan.projectMonitoring, icon: FolderKanban, group: 'planning', readiness: 'wired', experiences: ['executive_oversight', 'system_administration'] },
    users: { key: 'users', label: 'Users', href: portalRoutePlan.users, icon: UserCog, group: 'administration', readiness: 'integration_pending', permission: 'systemAdministration' },
    adminDepartments: { key: 'adminDepartments', label: 'Departments', href: portalRoutePlan.adminDepartments, icon: Building2, group: 'administration', readiness: 'integration_pending', permission: 'systemAdministration' },
    systemAdministration: { key: 'systemAdministration', label: 'System Administration', href: portalRoutePlan.systemAdministration, icon: Settings, group: 'administration', readiness: 'wired', permission: 'systemAdministration' },
    municipalSystems: { key: 'municipalSystems', label: 'Municipal Systems', href: portalRoutePlan.municipalSystems, icon: AppWindow, group: 'systems', readiness: 'integration_pending' },
};
