import {
    BookOpen,
    Building2,
    CalendarDays,
    FileSearch,
    FileText,
    FolderKanban,
    Inbox,
    Landmark,
    LayoutDashboard,
    ListChecks,
    Megaphone,
    MessageSquare,
    Network,
    Users,
} from 'lucide-react';
import type { PortalDestination, PortalDestinationKey } from './navigationTypes';

export const portalDestinations: Partial<Record<PortalDestinationKey, PortalDestination>> = {
    home: {
        key: 'home',
        label: 'Home',
        href: '/dashboard',
        icon: LayoutDashboard,
        group: 'home',
        readiness: 'wired',
        permission: 'dashboard',
    },
    myWork: {
        key: 'myWork',
        label: 'My Work',
        href: '/transactions',
        icon: FileText,
        group: 'work',
        readiness: 'wired',
        permission: 'transactions',
    },
    correspondence: {
        key: 'correspondence',
        label: 'Correspondence',
        href: '/correspondence',
        icon: Inbox,
        group: 'work',
        readiness: 'wired',
        permission: 'correspondence',
    },
    records: {
        key: 'records',
        label: 'Records',
        href: '/records',
        icon: FileSearch,
        group: 'work',
        readiness: 'wired',
        permission: 'records',
    },
    memoranda: {
        key: 'memoranda',
        label: 'Memoranda',
        href: '/memoranda',
        icon: FileText,
        group: 'work',
        readiness: 'wired',
        permission: 'memoranda',
    },
    announcements: {
        key: 'announcements',
        label: 'Announcements',
        href: '/announcements',
        icon: Megaphone,
        group: 'work',
        readiness: 'integration_pending',
    },
    calendar: {
        key: 'calendar',
        label: 'Calendar',
        href: '/calendar',
        icon: CalendarDays,
        group: 'work',
        readiness: 'wired',
    },
    meetings: {
        key: 'meetings',
        label: 'Meetings',
        href: '/meetings',
        icon: CalendarDays,
        group: 'work',
        readiness: 'integration_pending',
    },
    messages: {
        key: 'messages',
        label: 'Messages',
        href: '/messages',
        icon: MessageSquare,
        group: 'work',
        readiness: 'integration_pending',
    },
    executiveDepartments: {
        key: 'executiveDepartments',
        label: 'Executive Departments',
        href: '/departments',
        icon: Building2,
        group: 'organization',
        readiness: 'wired',
        permission: 'departments',
    },
    employeeDirectory: {
        key: 'employeeDirectory',
        label: 'Employee Directory',
        href: '/employees',
        icon: Users,
        group: 'organization',
        readiness: 'wired',
    },
    legislative: {
        key: 'legislative',
        label: 'Legislative',
        href: '/legislation',
        icon: Landmark,
        group: 'organization',
        readiness: 'wired',
    },
    localSpecialBodies: {
        key: 'localSpecialBodies',
        label: 'Local Special Bodies',
        href: '/local-special-bodies',
        icon: Network,
        group: 'organization',
        readiness: 'integration_pending',
    },
    developmentPlans: {
        key: 'developmentPlans',
        label: 'Development Plans',
        href: '/development-plans',
        icon: BookOpen,
        group: 'planning',
        readiness: 'integration_pending',
    },
    ppas: {
        key: 'ppas',
        label: 'PPAs',
        href: '/ppas',
        icon: ListChecks,
        group: 'planning',
        readiness: 'integration_pending',
    },
    projectMonitoring: {
        key: 'projectMonitoring',
        label: 'Project Monitoring',
        href: '/operations',
        icon: FolderKanban,
        group: 'planning',
        readiness: 'wired',
        experiences: ['executive_oversight', 'system_administration'],
    },
};
