import { router, useForm } from '@inertiajs/react';
import { FormEvent, useMemo, useState } from 'react';
import AppLayout from '../../layouts/AppLayout';

type Department = { id: number; code: string; name: string; short_name?: string | null };
type Employee = { id: number; employee_number: string; full_name: string };
type Asset = { id: number; property_number: string; qr_value: string; category: string; description: string; physical_location?: string | null; condition: string; status: string; reconciliation_status: string; current_department?: Department | null; accountable_employee?: Employee | null };
type InventorySession = { id: number; session_code: string; title: string; status: string; inventory_date: string; scans_count: number; department?: Department | null };
type Maintenance = { id: number; maintenance_type: string; status: string; issue_description: string; asset: Pick<Asset, 'id' | 'property_number' | 'description'> };
type Disposal = { id: number; status: string; reason: string; asset: Pick<Asset, 'id' | 'property_number' | 'description' | 'status'> };
type Props = { assets: Asset[]; inventorySessions: InventorySession[]; openMaintenance: Maintenance[]; pendingDisposals: Disposal[]; departments: Department[]; canManage: boolean; canReconcile: boolean };

export default function PropertyLifecycle({ assets, inventorySessions, openMaintenance, pendingDisposals, departments, canManage, canReconcile }: Props) {
    const inventory = useForm({ title: '', department_id: '', inventory_date: new Date().toISOString().slice(0, 10), notes: '' });
    const [selectedSession, setSelectedSession] = useState('');
    const [selectedAsset, setSelectedAsset] = useState('');
    const [scanValue, setScanValue] = useState('');
    const [location, setLocation] = useState('');
    const [condition, setCondition] = useState('good');
    const openSessions = useMemo(() => inventorySessions.filter(s => s.status === 'open'), [inventorySessions]);

    const submitInventory = (e: FormEvent) => { e.preventDefault(); inventory.post('/property/inventory', { preserveScroll: true, onSuccess: () => inventory.reset('title', 'department_id', 'notes') }); };
    const scan = () => {
        if (!selectedSession || !selectedAsset || !scanValue.trim()) return;
        router.post(`/property/inventory/${selectedSession}/assets/${selectedAsset}/scan`, { scan_value: scanValue.trim(), observed_location: location || null, observed_condition: condition }, { preserveScroll: true, onSuccess: () => setScanValue('') });
    };

    return <AppLayout title="Property Lifecycle"><div className="mx-auto max-w-7xl space-y-6">
        <section className="rounded-3xl bg-[#0b2852] p-6 text-white sm:p-8"><div className="text-xs font-bold uppercase tracking-[0.2em] text-blue-200">Phase 1 · M8</div><h1 className="mt-3 text-3xl font-bold">LGU Property Lifecycle</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-blue-100">Inventory sessions, QR/reference verification, maintenance, Accounting reconciliation, discrepancy evidence, and controlled disposal extend the existing PAR/ICS accountability ledger.</p></section>
        <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Assets', assets.length], ['Open inventory', openSessions.length], ['Maintenance', openMaintenance.length], ['Disposal review', pendingDisposals.length]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-2xl font-bold text-slate-950">{value}</div><div className="mt-1 text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</div></div>)}</section>

        {canManage && <section className="grid gap-6 xl:grid-cols-2">
            <form onSubmit={submitInventory} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-bold uppercase text-blue-700">Physical count</div><h2 className="mt-1 text-xl font-bold">Start inventory session</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required placeholder="Inventory title" value={inventory.data.title} onChange={e => inventory.setData('title', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm sm:col-span-2" /><select value={inventory.data.department_id} onChange={e => inventory.setData('department_id', e.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">Municipality-wide</option>{departments.map(d => <option key={d.id} value={d.id}>{d.short_name || d.name}</option>)}</select><input type="date" value={inventory.data.inventory_date} onChange={e => inventory.setData('inventory_date', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><textarea placeholder="Notes" value={inventory.data.notes} onChange={e => inventory.setData('notes', e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm sm:col-span-2" /></div><button disabled={inventory.processing} className="mt-4 rounded-xl bg-[#0b2852] px-4 py-2.5 text-sm font-semibold text-white">Start inventory</button></form>
            <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-bold uppercase text-blue-700">QR / reference verification</div><h2 className="mt-1 text-xl font-bold">Record inventory observation</h2><div className="mt-4 grid gap-3"><select value={selectedSession} onChange={e => setSelectedSession(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">Select open session</option>{openSessions.map(s => <option key={s.id} value={s.id}>{s.session_code} · {s.title}</option>)}</select><select value={selectedAsset} onChange={e => { setSelectedAsset(e.target.value); setScanValue(''); const a = assets.find(x => String(x.id) === e.target.value); setLocation(a?.physical_location || ''); setCondition(a?.condition || 'good'); }} className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">Select asset record</option>{assets.filter(a => a.status !== 'disposed').map(a => <option key={a.id} value={a.id}>{a.property_number} · {a.description}</option>)}</select><input placeholder="Scan QR / enter exact property reference" value={scanValue} onChange={e => setScanValue(e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><input placeholder="Observed location" value={location} onChange={e => setLocation(e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><select value={condition} onChange={e => setCondition(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="good">Good</option><option value="fair">Fair</option><option value="needs_repair">Needs repair</option><option value="unserviceable">Unserviceable</option></select><button onClick={scan} disabled={!selectedSession || !selectedAsset || !scanValue.trim()} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Verify and record</button></div></div>
        </section>}

        <section className="grid gap-6 xl:grid-cols-3"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Inventory sessions</h2><div className="mt-4 space-y-3">{inventorySessions.map(s => <div key={s.id} className="rounded-xl bg-slate-50 p-3 text-xs"><div className="font-semibold text-slate-900">{s.session_code}</div><div className="mt-1 text-slate-600">{s.title} · {s.scans_count} scans · {s.status}</div>{canManage && s.status === 'open' && <button onClick={() => router.post(`/property/inventory/${s.id}/close`, {}, { preserveScroll: true })} className="mt-2 font-semibold text-blue-700">Close session</button>}</div>)}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Open maintenance</h2><div className="mt-4 space-y-3">{openMaintenance.map(m => <div key={m.id} className="rounded-xl bg-amber-50 p-3 text-xs text-amber-900"><div className="font-semibold">{m.asset.property_number} · {m.asset.description}</div><div className="mt-1">{m.maintenance_type.replaceAll('_', ' ')} · {m.issue_description}</div>{canManage && <button onClick={() => router.post(`/property/maintenance/${m.id}/complete`, { condition_after: 'good' }, { preserveScroll: true })} className="mt-2 font-semibold text-amber-900">Mark completed / good</button>}</div>)}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Pending disposal</h2><div className="mt-4 space-y-3">{pendingDisposals.map(d => <div key={d.id} className="rounded-xl bg-rose-50 p-3 text-xs text-rose-900"><div className="font-semibold">{d.asset.property_number} · {d.asset.description}</div><div className="mt-1">Awaiting documented authority / decision</div></div>)}</div></div></section>
        <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><div className="text-xs font-bold uppercase text-blue-700">Asset state</div><h2 className="mt-1 text-xl font-bold">Lifecycle register</h2></div>{!canReconcile && <span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-bold uppercase text-slate-500">Accounting reconciliation read only</span>}</div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="pb-2 pr-4">Property</th><th className="pb-2 pr-4">Office</th><th className="pb-2 pr-4">Location</th><th className="pb-2 pr-4">Condition</th><th className="pb-2 pr-4">Status</th><th className="pb-2">Reconciliation</th></tr></thead><tbody className="divide-y divide-slate-100">{assets.map(a => <tr key={a.id}><td className="py-3 pr-4"><div className="font-semibold text-slate-900">{a.property_number}</div><div className="text-slate-500">{a.description}</div></td><td className="py-3 pr-4">{a.current_department?.short_name || a.current_department?.name || '—'}</td><td className="py-3 pr-4">{a.physical_location || '—'}</td><td className="py-3 pr-4">{a.condition.replaceAll('_', ' ')}</td><td className="py-3 pr-4">{a.status.replaceAll('_', ' ')}</td><td className="py-3">{a.reconciliation_status.replaceAll('_', ' ')}</td></tr>)}</tbody></table></div></section>
    </div></AppLayout>;
}
