import { CalendarDays, FileText, MapPin, UsersRound } from 'lucide-react';
import type { MunicipalMeeting } from '../../data/municipal/meetings';

const statusClass: Record<MunicipalMeeting['status'], string> = {
    Scheduled: 'bg-blue-50 text-blue-800 dark:bg-blue-950/40 dark:text-blue-200',
    Completed: 'bg-emerald-50 text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-200',
    Rescheduled: 'bg-amber-50 text-amber-800 dark:bg-amber-950/40 dark:text-amber-200',
};

export default function MeetingRegister({ meetings }: { meetings: MunicipalMeeting[] }) {
    if (!meetings.length) return <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500 dark:border-slate-700 dark:bg-[#142236] dark:text-slate-400">No meetings match the current filters.</div>;
    return <div className="grid gap-3 lg:grid-cols-2">{meetings.map((meeting) => <article key={meeting.id} className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-[#142236] sm:p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-[10px] font-bold uppercase tracking-wide text-blue-700 dark:text-blue-300">{meeting.id} · {meeting.organizingOffice}</div><h2 className="mt-1 text-base font-bold leading-5 text-slate-950 dark:text-slate-100">{meeting.title}</h2></div><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-bold ${statusClass[meeting.status]}`}>{meeting.status}</span></div><div className="mt-3 grid gap-2 text-xs sm:grid-cols-2"><div className="flex items-center gap-2 text-slate-600 dark:text-slate-300"><CalendarDays size={14} className="shrink-0 text-slate-400" />{meeting.date} · {meeting.time}</div><div className="flex items-center gap-2 text-slate-600 dark:text-slate-300"><MapPin size={14} className="shrink-0 text-slate-400" />{meeting.venue}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><div className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wide text-slate-400"><UsersRound size={12} /> Participants</div><div className="mt-1 text-xs leading-5 text-slate-600 dark:text-slate-300">{meeting.participants.join(' · ')}</div></div><div><div className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wide text-slate-400"><FileText size={12} /> Related documents</div><div className="mt-1 text-xs leading-5 text-slate-600 dark:text-slate-300">{meeting.relatedDocuments.join(' · ')}</div></div></div><div className="mt-4 border-t border-slate-100 pt-3 dark:border-slate-700"><div className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Agenda</div><ol className="mt-1 space-y-1 text-xs leading-5 text-slate-600 dark:text-slate-300">{meeting.agenda.map((item, index) => <li key={item}>{index + 1}. {item}</li>)}</ol></div></article>)}</div>;
}
