import { CalendarClock, FileText } from 'lucide-react';
import type { MunicipalCalendarItem } from '../../data/municipal/meetingsCalendar';

export default function MunicipalCalendarAgenda({ items }: { items: MunicipalCalendarItem[] }) {
    return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-[#142236]" aria-label="Municipal planning reference schedule">
        <div className="flex items-start justify-between gap-3 border-b border-slate-100 px-4 py-3 dark:border-slate-700"><div><div className="text-xs font-bold uppercase tracking-wide text-blue-700 dark:text-blue-300">Planning reference</div><h2 className="mt-0.5 font-bold text-slate-950 dark:text-slate-100">Meetings and office deadlines</h2><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Municipal planning-reference items maintained separately from the live routed-work calendar above.</p></div><div className="shrink-0 text-sm font-bold text-slate-700 dark:text-slate-200">{items.length} items</div></div>
        <div className="max-h-[520px] divide-y divide-slate-100 overflow-y-auto dark:divide-slate-700">{items.map((item) => <article key={item.id} className="grid gap-2 px-4 py-3 sm:grid-cols-[118px_1fr_auto] sm:items-center"><div><div className="text-xs font-bold text-slate-900 dark:text-slate-100">{item.date}</div><div className="mt-0.5 flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400"><CalendarClock size={11} aria-hidden="true" />{item.time}</div></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${item.kind === 'Meeting' ? 'bg-blue-50 text-blue-800 dark:bg-blue-950/40 dark:text-blue-200' : 'bg-amber-50 text-amber-800 dark:bg-amber-950/40 dark:text-amber-200'}`}>{item.kind}</span>{item.priority === 'High' && <span className="text-[10px] font-bold uppercase text-rose-700 dark:text-rose-300">High priority</span>}</div><div className="mt-1 text-sm font-semibold text-slate-950 dark:text-slate-100">{item.title}</div><div className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{item.office}</div></div><div className="flex max-w-[260px] items-start gap-1 text-xs text-slate-500 dark:text-slate-400"><FileText size={12} className="mt-0.5 shrink-0" aria-hidden="true" />{item.relatedRecord}</div></article>)}</div>
    </section>;
}
