import { Link, router } from '@inertiajs/react';
import AppLayout from '../../../layouts/AppLayout';

type Task = { id: number; task_key: string; title: string; category: string; is_required: boolean; status: string; due_at?: string | null; completed_at?: string | null; notes?: string | null; owner_department?: { name: string; short_name?: string | null } | null; completer?: { name: string } | null };
type Props = { case: { id: number; status: string; appointment_reference?: string | null; planned_start_date?: string | null; employee: any; target_department: any; supervisor?: any; tasks: Task[] }; summary: { required: number; completed: number; openRequired: number } };

export default function OnboardingShow({ case: onboardingCase, summary }: Props) {
    const completeTask = (task: Task) => router.post(`/hris/admin/lifecycle/onboarding/tasks/${task.id}/complete`, {}, { preserveScroll: true });
    const completeCase = () => router.post(`/hris/admin/lifecycle/onboarding/${onboardingCase.id}/complete`, {}, { preserveScroll: true });

    return <AppLayout title="Onboarding Case"><div className="mx-auto max-w-5xl space-y-6">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><Link href="/hris/admin/lifecycle" className="text-sm font-semibold text-blue-700">← Employee lifecycle</Link><span className="w-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-bold uppercase text-slate-700">{onboardingCase.status.replaceAll('_', ' ')}</span></div>

        <section className="rounded-3xl bg-[#0b2852] p-6 text-white sm:p-8"><div className="text-xs font-bold uppercase tracking-[0.18em] text-blue-200">{onboardingCase.employee.employee_number}</div><h1 className="mt-2 text-3xl font-bold">{onboardingCase.employee.full_name}</h1><p className="mt-2 text-sm text-blue-100">{onboardingCase.employee.position_title} · {onboardingCase.target_department.short_name || onboardingCase.target_department.name}</p><div className="mt-5 grid grid-cols-3 gap-3"><div className="rounded-xl bg-white/10 p-3"><div className="text-xl font-bold">{summary.required}</div><div className="text-[10px] uppercase text-blue-200">Required</div></div><div className="rounded-xl bg-white/10 p-3"><div className="text-xl font-bold">{summary.completed}</div><div className="text-[10px] uppercase text-blue-200">Completed</div></div><div className="rounded-xl bg-white/10 p-3"><div className="text-xl font-bold">{summary.openRequired}</div><div className="text-[10px] uppercase text-blue-200">Blockers</div></div></div></section>

        <section className="rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">Activation checklist</h2><p className="mt-1 text-xs text-slate-500">Required tasks must be completed or formally waived before employee activation.</p></div><div className="divide-y divide-slate-100">{onboardingCase.tasks.map(task => <div key={task.id} className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-semibold text-slate-950">{task.title}</span>{task.is_required && <span className="rounded bg-rose-50 px-1.5 py-0.5 text-[9px] font-bold uppercase text-rose-700">Required</span>}</div><div className="mt-1 text-xs text-slate-500">{task.category.replaceAll('_', ' ')} · Owner: {task.owner_department?.short_name || task.owner_department?.name || 'HR administration'}</div>{task.completed_at && <div className="mt-1 text-[10px] text-emerald-700">Completed {new Date(task.completed_at).toLocaleString()}{task.completer?.name ? ` by ${task.completer.name}` : ''}</div>}</div><div>{task.status === 'pending' ? <button onClick={() => completeTask(task)} className="rounded-xl bg-blue-700 px-3 py-2 text-xs font-semibold text-white">Mark complete</button> : <span className={`rounded-full px-2.5 py-1 text-[9px] font-bold uppercase ${task.status === 'completed' ? 'bg-emerald-50 text-emerald-800' : 'bg-slate-100 text-slate-600'}`}>{task.status.replaceAll('_', ' ')}</span>}</div></div></div>)}</div></section>

        <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">Activate employment record</h2><p className="mt-1 text-xs leading-5 text-slate-500">Activation also enables the linked portal identity. The service rejects this action while required blockers remain open.</p></div><button onClick={completeCase} disabled={onboardingCase.status === 'completed'} className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Complete onboarding</button></div></section>
    </div></AppLayout>;
}
