import { Link, router, useForm } from '@inertiajs/react';
import { Activity, Building2, LockKeyhole, RotateCcw, Search, ShieldCheck, Users } from 'lucide-react';
import type { ChangeEvent, FormEvent, ReactNode } from 'react';
import PageFrame from '../../components/PageFrame';
import PageHeader from '../../components/PageHeader';
import AppLayout from '../../layouts/AppLayout';

type Overview = { totalEmployees:number; portalUsers:number; activeUsers:number; inactiveUsers:number; employeesWithoutPortalAccounts:number; activeDepartments:number; privilegedUsers:number; mfaEnrolled:number };
type Department = { id:number; code:string; name:string; shortName:string|null };
type RegistryRow = { employee:string|null; employeeNumber:string|null; department:Omit<Department,'id'>|null; position:string|null; role:string|null; loginEmail:string; active:boolean; mfaEnrolled:boolean };
type PageLink = { url:string|null; label:string; active:boolean };
type Registry = { data:RegistryRow[]; total:number; current_page:number; last_page:number; per_page:number; links:PageLink[] };
type OfficeIdentity = { office:string; code:string; shortName:string|null; officialEmail:string|null; status:string };
type OperationSummary = { activeMunicipalWork?:number; municipalOverdue?:number; municipalUnassigned?:number; dueSoon?:number; executiveQueue?:number; completedThisMonth?:number };
type DepartmentWorkload = { id:number; code:string; name:string; shortName:string|null; active:number; unassigned:number; dueSoon:number; overdue:number };
type SecurityEvent = { actor:string|null; action:string; outcome:string; summary:string; createdAt:string|null };
type Security = { privilegedAccounts:number; mfaEnrolled:number; inactiveAccounts:number; recentEvents:SecurityEvent[] };
type Filters = { search:string; department_id:string; role:string; status:string };
type Props = { overview:Overview; registry:Registry; registryFilters:{search:string;department_id:number|null;role:string;status:string}; departmentOptions:Department[]; roleOptions:string[]; officeIdentities:OfficeIdentity[]; operations:{summary:OperationSummary;departmentWorkload:DepartmentWorkload[]}; security:Security };

const label = (value:string) => value.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase());
const fieldClass = 'w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-100 dark:focus:ring-blue-900';
const insetSurface = 'border-slate-200 bg-white dark:border-slate-700 dark:bg-[#142236]';

export default function AdminIndex({ overview, registry, registryFilters, departmentOptions, roleOptions, officeIdentities, operations, security }:Props) {
    const { data,setData,get,processing } = useForm<Filters>({ search:registryFilters.search??'', department_id:registryFilters.department_id?.toString()??'', role:registryFilters.role??'', status:registryFilters.status??'' });
    const applyFilters=(event:FormEvent)=>{event.preventDefault();get('/admin',{preserveScroll:true,preserveState:true,replace:true});};
    const clearFilters=()=>router.get('/admin',{}, {preserveScroll:true,replace:true});
    const overviewCards=[['Portal users',overview.portalUsers],['Active accounts',overview.activeUsers],['Inactive accounts',overview.inactiveUsers],['MFA enrolled',overview.mfaEnrolled],['Employees',overview.totalEmployees],['Without portal account',overview.employeesWithoutPortalAccounts],['Active offices',overview.activeDepartments],['Privileged accounts',overview.privilegedUsers]] as const;
    const operationCards=[['Active municipal work',operations.summary.activeMunicipalWork??0],['Overdue',operations.summary.municipalOverdue??0],['Unassigned',operations.summary.municipalUnassigned??0],['Completed this month',operations.summary.completedThisMonth??0]] as const;

    return <AppLayout title="Accounts & Access"><PageFrame>
        <PageHeader eyebrow="Platform identity and security" title="Accounts & Access" description="Review portal identities, role assignment, account state, MFA enrollment, and office digital identity. Administrative access does not expand access to confidential municipal content." icon={ShieldCheck} />

        <Section title="Access summary" icon={<Users size={17}/>} description="Current account and identity totals from the portal registry.">
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{overviewCards.map(([name,value])=><Metric key={name} label={name} value={value}/>)}</div>
        </Section>

        <Section title="Account registry" icon={<Users size={17}/>} description="Search authorized portal identities and review role, account state, and MFA status. Results remain server-filtered and paginated.">
            <form onSubmit={applyFilters} aria-label="Account registry filters" className="grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/40 sm:grid-cols-2 lg:grid-cols-4">
                <label className="min-w-0 text-xs font-semibold text-slate-600 dark:text-slate-300 lg:col-span-2">Search identity
                    <div className="relative mt-1.5"><Search className="absolute left-3 top-3 text-slate-400 dark:text-slate-400" size={15}/><input value={data.search} onChange={(event:ChangeEvent<HTMLInputElement>)=>setData('search',event.target.value)} className={`${fieldClass} pl-9`} placeholder="Employee, employee number, or login email"/></div>
                </label>
                <Filter label="Office" value={data.department_id} onChange={value=>setData('department_id',value)}><option value="">All offices</option>{departmentOptions.map(department=><option key={department.id} value={department.id}>{department.shortName||department.name}</option>)}</Filter>
                <Filter label="Portal role" value={data.role} onChange={value=>setData('role',value)}><option value="">All roles</option>{roleOptions.map(role=><option key={role} value={role}>{label(role)}</option>)}</Filter>
                <Filter label="Account status" value={data.status} onChange={value=>setData('status',value)}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></Filter>
                <div className="flex flex-wrap items-end gap-2 sm:col-span-2 lg:col-span-3"><button disabled={processing} className="inline-flex items-center gap-2 rounded-xl bg-[#0b2852] px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-60"><Search size={14}/>Apply filters</button><button type="button" onClick={clearFilters} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-xs font-semibold text-slate-700 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-200"><RotateCcw size={14}/>Clear</button></div>
            </form>

            <div className="mt-4 overflow-hidden rounded-xl border border-slate-200 dark:border-slate-700">
                <div className="flex items-center justify-between gap-3 border-b border-slate-200 bg-white px-4 py-3 text-xs text-slate-500 dark:border-slate-700 dark:bg-[#142236] dark:text-slate-400"><span>Portal identities</span><span className="shrink-0 font-semibold">{registry.total.toLocaleString()} accounts</span></div>
                {registry.data.length===0 ? <div className="bg-white px-5 py-10 text-center text-sm text-slate-500 dark:bg-[#142236] dark:text-slate-400">No accounts match the current filters.</div> : <>
                    <div className="divide-y divide-slate-100 bg-white dark:divide-slate-700 dark:bg-[#142236] md:hidden">{registry.data.map((row,index)=><AccountCard key={`${row.loginEmail}-${index}`} row={row}/>)}</div>
                    <div className="hidden overflow-x-auto md:block"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-900/40 dark:text-slate-400"><tr>{['Employee','Employee no.','Office','Position','Portal role','Login email','Status','MFA'].map(heading=><th key={heading} className="px-4 py-3 font-bold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 bg-white dark:divide-slate-700 dark:bg-[#142236]">{registry.data.map((row,index)=><tr key={`${row.loginEmail}-${index}`} className="align-top hover:bg-slate-50 dark:hover:bg-slate-800/50"><td className="max-w-52 px-4 py-3 font-semibold text-slate-950 dark:text-slate-100">{row.employee||'Unlinked portal user'}</td><td className="px-4 py-3 text-slate-600 dark:text-slate-300">{row.employeeNumber||'—'}</td><td className="max-w-44 px-4 py-3 text-slate-600 dark:text-slate-300">{row.department?.shortName||row.department?.name||'—'}</td><td className="max-w-48 px-4 py-3 text-slate-600 dark:text-slate-300">{row.position||'—'}</td><td className="px-4 py-3 text-slate-600 dark:text-slate-300">{row.role?label(row.role):'—'}</td><td className="max-w-56 break-all px-4 py-3 text-slate-600 dark:text-slate-300">{row.loginEmail}</td><td className="px-4 py-3"><Status ok={row.active} yes="Active" no="Inactive"/></td><td className="px-4 py-3"><Status ok={row.mfaEnrolled} yes="Enrolled" no="Not enrolled" neutral/></td></tr>)}</tbody></table></div>
                </>}
                {registry.last_page>1 && <nav aria-label="Account registry pages" className="flex flex-wrap gap-1 border-t border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-[#142236]">{registry.links.map((page,index)=>page.url?<Link key={`${page.label}-${index}`} href={page.url} preserveScroll className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${page.active?'bg-blue-700 text-white':'border border-slate-200 text-slate-600 dark:border-slate-600 dark:text-slate-300'}`} dangerouslySetInnerHTML={{__html:page.label}}/>:<span key={`${page.label}-${index}`} className="rounded-lg px-3 py-1.5 text-xs text-slate-300 dark:text-slate-600" dangerouslySetInnerHTML={{__html:page.label}}/>)}</nav>}
            </div>
        </Section>

        <div className="grid gap-4 xl:grid-cols-2">
            <Section title="Office digital identity" icon={<Building2 size={17}/>} description="Official office login identities are shown only when explicitly configured.">
                <div className="max-h-[420px] divide-y divide-slate-100 overflow-y-auto rounded-xl border border-slate-200 bg-white dark:divide-slate-700 dark:border-slate-700 dark:bg-[#142236]">{officeIdentities.map(office=><div key={office.code} className="flex min-w-0 flex-col gap-1 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="break-words text-sm font-semibold text-slate-950 dark:text-slate-100">{office.shortName||office.office}</div><div className="text-xs text-slate-500 dark:text-slate-400">{office.code}</div></div><div className="min-w-0 sm:max-w-[55%] sm:text-right"><div className="break-all text-xs font-semibold text-slate-700 dark:text-slate-300">{office.officialEmail||'Awaiting official office email registry'}</div><div className="mt-0.5 text-xs text-slate-400 dark:text-slate-400">{office.status}</div></div></div>)}</div>
            </Section>

            <Section title="Security status" icon={<LockKeyhole size={17}/>} description="Authentication and security metadata within system-administration scope.">
                <div className="grid grid-cols-3 gap-2"><Metric label="Privileged" value={security.privilegedAccounts}/><Metric label="MFA enrolled" value={security.mfaEnrolled}/><Metric label="Inactive" value={security.inactiveAccounts}/></div>
                <div className="mt-3 divide-y divide-slate-100 rounded-xl border border-slate-200 bg-white dark:divide-slate-700 dark:border-slate-700 dark:bg-[#142236]">{security.recentEvents.length===0?<div className="px-4 py-7 text-center text-xs text-slate-500 dark:text-slate-400">No recent authentication or security activity.</div>:security.recentEvents.map((event,index)=><div key={`${event.action}-${event.createdAt}-${index}`} className="px-4 py-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="break-words text-xs font-semibold text-slate-900 dark:text-slate-100">{event.actor||'System'} · {label(event.action)}</div><div className="mt-1 break-words text-xs leading-5 text-slate-500 dark:text-slate-400">{event.summary}</div></div><Status ok={event.outcome==='allowed'} yes="Allowed" no={label(event.outcome)} neutral/></div>{event.createdAt&&<time className="mt-1 block text-xs text-slate-400 dark:text-slate-400" dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString()}</time>}</div>)}</div>
                <Link href="/audit" className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-blue-700 hover:underline dark:text-blue-300"><ShieldCheck size={14}/>Open Audit & Security</Link>
            </Section>
        </div>

        <Section title="Municipal operations context" icon={<Activity size={17}/>} description="Bounded transaction aggregates for platform context. This does not grant access to restricted correspondence or private records.">
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{operationCards.map(([name,value])=><Metric key={name} label={name} value={value}/>)}</div>
            <div className="mt-4 divide-y divide-slate-100 rounded-xl border border-slate-200 bg-white dark:divide-slate-700 dark:border-slate-700 dark:bg-[#142236] md:hidden">{operations.departmentWorkload.map(office=><article key={office.id} className="px-4 py-3"><div className="break-words text-xs font-bold text-slate-900 dark:text-slate-100">{office.shortName||office.name}</div><div className="mt-2 grid grid-cols-2 gap-2 text-xs text-slate-600 dark:text-slate-300"><div><span className="font-bold text-slate-900 dark:text-slate-100">{office.active}</span> active</div><div><span className="font-bold text-slate-900 dark:text-slate-100">{office.unassigned}</span> unassigned</div><div><span className="font-bold text-amber-700 dark:text-amber-300">{office.dueSoon}</span> due soon</div><div><span className="font-bold text-rose-700 dark:text-rose-300">{office.overdue}</span> overdue</div></div></article>)}</div>
            <div className="mt-4 hidden overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-700 md:block"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-900/40 dark:text-slate-400"><tr><th className="px-4 py-3">Office</th><th className="px-4 py-3">Active</th><th className="px-4 py-3">Unassigned</th><th className="px-4 py-3">Due soon</th><th className="px-4 py-3">Overdue</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white dark:divide-slate-700 dark:bg-[#142236]">{operations.departmentWorkload.map(office=><tr key={office.id}><td className="px-4 py-3 font-semibold text-slate-900 dark:text-slate-100">{office.shortName||office.name}</td><td className="px-4 py-3 text-slate-700 dark:text-slate-300">{office.active}</td><td className="px-4 py-3 text-slate-700 dark:text-slate-300">{office.unassigned}</td><td className="px-4 py-3 text-slate-700 dark:text-slate-300">{office.dueSoon}</td><td className="px-4 py-3 font-semibold text-rose-700 dark:text-rose-300">{office.overdue}</td></tr>)}</tbody></table></div>
        </Section>
    </PageFrame></AppLayout>;
}

function AccountCard({row}:{row:RegistryRow}) { return <article className="min-w-0 px-4 py-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words text-sm font-bold text-slate-950 dark:text-slate-100">{row.employee||'Unlinked portal user'}</h3><div className="mt-0.5 break-all text-xs text-slate-500 dark:text-slate-400">{row.loginEmail}</div></div><Status ok={row.active} yes="Active" no="Inactive"/></div><dl className="mt-3 grid grid-cols-2 gap-x-3 gap-y-2 text-xs"><div><dt className="font-bold uppercase text-slate-400 dark:text-slate-400">Employee no.</dt><dd className="mt-0.5 break-words text-slate-700 dark:text-slate-300">{row.employeeNumber||'—'}</dd></div><div><dt className="font-bold uppercase text-slate-400 dark:text-slate-400">Office</dt><dd className="mt-0.5 break-words text-slate-700 dark:text-slate-300">{row.department?.shortName||row.department?.name||'—'}</dd></div><div><dt className="font-bold uppercase text-slate-400 dark:text-slate-400">Role</dt><dd className="mt-0.5 break-words text-slate-700 dark:text-slate-300">{row.role?label(row.role):'—'}</dd></div><div><dt className="font-bold uppercase text-slate-400 dark:text-slate-400">MFA</dt><dd className="mt-0.5"><Status ok={row.mfaEnrolled} yes="Enrolled" no="Not enrolled" neutral/></dd></div></dl>{row.position&&<div className="mt-2 break-words text-xs text-slate-500 dark:text-slate-400">{row.position}</div>}</article>; }
function Section({title,description,icon,children}:{title:string;description:string;icon:ReactNode;children:ReactNode}) { return <section className={`rounded-xl border p-4  transition-colors sm:p-5 ${insetSurface}`}><div className="mb-4 flex items-start gap-3"><div className="mt-0.5 rounded-xl bg-blue-50 p-2 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300">{icon}</div><div className="min-w-0"><h2 className="font-bold text-slate-950 dark:text-slate-100">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">{description}</p></div></div>{children}</section>; }
function Metric({label:text,value}:{label:string;value:number}) { return <div className="min-w-0 rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 dark:border-slate-700 dark:bg-slate-900/40"><div className="text-xl font-bold text-slate-950 dark:text-slate-100 sm:text-2xl">{value.toLocaleString()}</div><div className="mt-1 break-words text-xs font-medium leading-4 text-slate-500 dark:text-slate-400 sm:text-xs">{text}</div></div>; }
function Status({ok,yes,no,neutral=false}:{ok:boolean;yes:string;no:string;neutral?:boolean}) { return <span className={`inline-flex shrink-0 rounded-full px-2 py-1 text-xs font-bold ${ok?'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300':neutral?'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300':'bg-rose-50 text-rose-700 dark:bg-rose-950/40 dark:text-rose-300'}`}>{ok?yes:no}</span>; }
function Filter({label:text,value,onChange,children}:{label:string;value:string;onChange:(value:string)=>void;children:ReactNode}) { return <label className="min-w-0 text-xs font-semibold text-slate-600 dark:text-slate-300">{text}<select value={value} onChange={(event:ChangeEvent<HTMLSelectElement>)=>onChange(event.target.value)} className={`mt-1.5 ${fieldClass}`}>{children}</select></label>; }
